apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-weather-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: weather.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-weather-service
            port:
              number: 5000
