apiVersion: v1
kind: Service
metadata:
  name: flask-weather-service
  labels:
    app: flask-weather-app
spec:
  type: NodePort
  selector:
    app: flask-weather-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30008
